#!/usr/bin/env bash

set -euo pipefail

BACKUP="/tmp/minepanel-worlds-$(date +%Y-%m-%d_%H-%M-%S).tar.gz"
SERVER_DIR="/var/lib/docker/volumes/game-hosting-minepanel-rchbtm_minepanel-servers/_data/jai-port"
trap 'rm -f "$BACKUP"' EXIT

tar -chzf "$BACKUP" \
  -C "$SERVER_DIR" \
  mc-data

rclone copy "$BACKUP" \
  gdrive:Dokploy-Backups/MinePanel/worlds \
  --config "/home/${SUDO_USER:-$USER}/.config/rclone/rclone.conf" \
  --progress
